### ISSUE TITLE
pymysql lib missing when using the container in docker-compose

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/chanjo#222]
![image](https://user-images.githubusercontent.com/28093618/99258147-6abc8d00-2818-11eb-8410-42dbc3464be6.png)

**Comment by moonso** [comment]
Yes this is weird, I have also encountered this when connecting to mysql with SQLAlchemy...

**Comment by northwestwitch** [comment]
I'm going to fix it by adding it to the dependencies on my next PR (incoming today)
