### ISSUE TITLE
Dead link to documentation in README

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/chanjo#231]
The README links to this url http://www.clinicalgenomics.se/chanjo/ which 404s

**Comment by moonso** [comment]
Thx, we need to redirect the build in https://github.com/Clinical-Genomics/chanjo/blob/6605989d1efe41c44a1e22eff8d5ce1fab16f172/mkdocs.yml#L3 to https://clinical-genomics.github.io/scout and also change the link in README
