### ISSUE TITLE
Replace deprecated Alchy with SQLAlchemy

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/chanjo#251]
Alchy is discontinued and integrating chanjo in other software prevents software upgrades, see

- https://github.com/Clinical-Genomics/scout/issues/4614
- https://github.com/Clinical-Genomics/scout/issues/4101

**Comment by dnil** [comment]
Perhaps https://github.com/dgilland/sqlservice would be useful as well; I noticed we have snuck it into the chanjo-report requirements. Good to relieve the tedium of base model creation and what not..

**Comment by northwestwitch** [comment]
I'm working on this but I've realised that it's a complicated task. Many changed all over the place, plus other deprecated libs and code to be updated. I'm not saying that you might as well re-write it, but kind-of
